import { BLOCKS } from "../biome/constants.js";

export const EXTRA_BLOCKS = Object.freeze({
  FLOWING_WATER: 8,
  COBBLESTONE: 4,
  GOLD_ORE: 14,
  IRON_ORE: 15,
  COAL_ORE: 16,
  OAK_LOG: 17,
  OAK_LEAVES: 18,
  LAPIS_ORE: 21,
  TALL_GRASS: 31,
  DEAD_BUSH: 32,
  YELLOW_FLOWER: 37,
  RED_FLOWER: 38,
  BROWN_MUSHROOM: 39,
  RED_MUSHROOM: 40,
  MOSSY_COBBLESTONE: 48,
  MOB_SPAWNER: 52,
  CHEST: 54,
  DIAMOND_ORE: 56,
  REDSTONE_ORE: 73,
  FLOWING_LAVA: 10,
  LAVA: 11,
  CACTUS: 81,
  CLAY: 82,
  REEDS: 83,
  PUMPKIN: 86,
  BIRCH_LOG: 201,
  SPRUCE_LOG: 202,
  BIRCH_LEAVES: 203,
  SPRUCE_LEAVES: 204,
  SNOW_LAYER: 205,
});

export const BLOCK_ROLE_IDS = Object.freeze({
  ...BLOCKS,
  ...EXTRA_BLOCKS,
});

export const BEDROCK_BLOCK_MAP = Object.freeze({
  [EXTRA_BLOCKS.FLOWING_WATER]: "minecraft:flowing_water",
  [BLOCKS.AIR]: "minecraft:air",
  [EXTRA_BLOCKS.COBBLESTONE]: "minecraft:cobblestone",
  [BLOCKS.STONE]: "minecraft:stone",
  [BLOCKS.GRASS]: "minecraft:grass_block",
  [BLOCKS.DIRT]: "minecraft:dirt",
  [BLOCKS.BEDROCK]: "minecraft:bedrock",
  [BLOCKS.WATER]: "minecraft:water",
  [BLOCKS.SAND]: "minecraft:sand",
  [BLOCKS.GRAVEL]: "minecraft:gravel",
  [BLOCKS.SANDSTONE]: "minecraft:sandstone",
  [EXTRA_BLOCKS.TALL_GRASS]: "minecraft:tallgrass",
  [EXTRA_BLOCKS.DEAD_BUSH]: "minecraft:deadbush",
  [EXTRA_BLOCKS.YELLOW_FLOWER]: "minecraft:yellow_flower",
  [EXTRA_BLOCKS.RED_FLOWER]: "minecraft:red_flower",
  [EXTRA_BLOCKS.BROWN_MUSHROOM]: "minecraft:brown_mushroom",
  [EXTRA_BLOCKS.RED_MUSHROOM]: "minecraft:red_mushroom",
  [EXTRA_BLOCKS.MOSSY_COBBLESTONE]: "minecraft:mossy_cobblestone",
  [EXTRA_BLOCKS.MOB_SPAWNER]: "minecraft:mob_spawner",
  [EXTRA_BLOCKS.CHEST]: "minecraft:chest",
  [EXTRA_BLOCKS.GOLD_ORE]: "minecraft:gold_ore",
  [EXTRA_BLOCKS.IRON_ORE]: "minecraft:iron_ore",
  [EXTRA_BLOCKS.COAL_ORE]: "minecraft:coal_ore",
  [EXTRA_BLOCKS.OAK_LOG]: "minecraft:oak_log",
  [EXTRA_BLOCKS.OAK_LEAVES]: "minecraft:oak_leaves",
  [EXTRA_BLOCKS.LAPIS_ORE]: "minecraft:lapis_ore",
  [EXTRA_BLOCKS.DIAMOND_ORE]: "minecraft:diamond_ore",
  [EXTRA_BLOCKS.REDSTONE_ORE]: "minecraft:redstone_ore",
  [EXTRA_BLOCKS.FLOWING_LAVA]: "minecraft:flowing_lava",
  [EXTRA_BLOCKS.LAVA]: "minecraft:lava",
  [EXTRA_BLOCKS.CLAY]: "minecraft:clay",
  [EXTRA_BLOCKS.CACTUS]: "minecraft:cactus",
  [EXTRA_BLOCKS.REEDS]: "minecraft:reeds",
  [EXTRA_BLOCKS.PUMPKIN]: "minecraft:pumpkin",
  [EXTRA_BLOCKS.BIRCH_LOG]: "minecraft:birch_log",
  [EXTRA_BLOCKS.SPRUCE_LOG]: "minecraft:spruce_log",
  [EXTRA_BLOCKS.BIRCH_LEAVES]: "minecraft:birch_leaves",
  [EXTRA_BLOCKS.SPRUCE_LEAVES]: "minecraft:spruce_leaves",
  [EXTRA_BLOCKS.SNOW_LAYER]: "minecraft:snow_layer",
  [BLOCKS.ICE]: "minecraft:ice",
});

export const DEFAULT_BLOCK_PALETTE = Object.freeze(
  Object.fromEntries(
    Object.entries(BLOCK_ROLE_IDS)
      .filter(([, blockId]) => BEDROCK_BLOCK_MAP[blockId] !== undefined)
      .map(([roleName, blockId]) => [roleName, BEDROCK_BLOCK_MAP[blockId]]),
  ),
);
